### PR TITLE
added support to cjs

### PR DESCRIPTION
**Pull request by kvnglvz**
Added support for CJS.

I just followed this tutorial on how to do it with rollup.
[https://stackoverflow.com/questions/74937600/how-to-support-es-modules-and-commonjs-modules-at-the-same-time](url)

Note: This is my very first contribution ever, please tell me if something is wrong with my PR. Thank you.

### CODE REVIEW

**Comment by adrienjoly** [comment]
Thanks for your contribution.

I'm a bit skeptical on what practical improvements these changes bring for users of this lib. Can you clarify what motivated you to make these changes?

**Comment by adrienjoly** [comment]
Note: if the index.cjs file is generated by a npm script, we may want to make it run automatically for every new version of pdfreader => call that command from the release script and don't necessarily keep the generated file in the git repo.

**Comment by treeslikemedia** [comment]
I have a commonJS project i was hoping to use this in. Any reason this never got merged / still isn't supported?

**Comment by adrienjoly** [comment]
@treeslikemedia Did you try following these instructions? https://adamcoster.com/blog/commonjs-and-esm-importexport-compatibility-examples#importing-esm-into-commonjs-cjs

**Pull request closed without merging**
