### PR TITLE
Fix for for in loop

### PR DESCRIPTION
**Pull request by narendrabuddiga**
fix for for-in loop 
not to iterate for "Equals"condtion

### CODE REVIEW

**Comment by adrienjoly** [comment]
Hi thanks for proposing a pull requests!

Can you provide steps (or automated test) to reproduce the bug that your PR intends to fix, and make sure that your changes respect the indentation and formatting rules of the rest of the code base, please?

**Comment by narendrabuddiga** [comment]
hai Joly,
             i have attached the screen shots of the error that caused
while i'm using npm PdfReader Module
the loop cause an issue at the end of the data page it is going on
iteration for "equals" to value
and it is giving the iterate variable as undefined and causing exiting the
loop
the issue is cause only when i used parseBuffer function to reader file in
database

thanks
Narendra

**Comment by adrienjoly** [comment]
The `t !== "equals"` condition looks like it may not make sense for *all* PDF buffers...

This may explain why automated fails on this PR. (https://github.com/adrienjoly/npm-pdfreader/pull/44/checks?check_run_id=608148664)

=> Can you share the PDF file (or buffer saved as a file) for which you need this change, please?

**Comment by adrienjoly** [comment]
No news for several months => closing this PR.

**Pull request closed without merging**
