### PR TITLE
Added type definations for class 'rule' to get ts support.

### PR DESCRIPTION
**Pull request by Basavarajrp**
# Add TypeScript Declarations for Rule Class. 

This was related to [issue](https://github.com/adrienjoly/npm-pdfreader/issues/135). I just added the type definition for the Rule class alone.

### CODE REVIEW

**Review by adrienjoly — DISMISSED** [review]
Thank you for adding types!

Can you just reformat the file using `npm run prettier:fix` and commit, before we merge the PR, please?

**Comment by Basavarajrp** [comment]
> Thank you for adding types!
> 
> Can you just reformat the file using `npm run prettier:fix` and commit, before we merge the PR, please?

Done @adrienjoly

**Review by adrienjoly — APPROVED** [review]

**Comment by Basavarajrp** [comment]
@adrienjoly I'm happy to see my first open source PR getting merged! This is my first open source contribution. Thank you so much!

**Comment by adrienjoly** [comment]
Congrats! 🎉
Good job and thank you for your contribution :-)

**Comment by CalderWhite** [comment]
You need to publish a release for people to use this feature. The latest npm release doesn't have this, and when you try to use the git repo there are module issues since the ci `build:cjs` step is required to add support here.

I am using my [own fork](https://www.npmjs.com/package/cwhite-pdfreader) of this in the meantime. I'll take it down once the release is published to npm.

**Comment by adrienjoly** [comment]
@CalderWhite thanks for the heads up! the release didn't work because I had forgotten to rename your PR as a semantic commit => the release manager didn't know if it had to increment the patch, minor or major part of the version.

**Comment by CalderWhite** [comment]
Not my change, but happy to take credit! 😆 . Thanks for the quick response!

**Pull request merged**
